# Generated by Django 4.0.1 on 2022-08-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Ad',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
