# Generated by Django 4.0.1 on 2022-08-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_location_alter_ad_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='ads/images/'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
