# Generated by Django 4.0.1 on 2022-08-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_rename_category_id_ad_category_alter_ad_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['id'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
