# Generated by Django 4.0.1 on 2022-08-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(),
        ),
    ]
