# Generated by Django 4.0.1 on 2022-08-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_remove_ad_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='category',
            new_name='category_id',
        ),
    ]
