# Generated by Django 4.0.1 on 2022-08-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_rename_author_ad_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='category_id',
            new_name='category',
        ),
    ]
